services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./backend:/var/www/html/backend
      - ./docker/apache-config.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - UPDATE_SECRET=secure_crypto_key
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-crypto_db}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql-data: