CREATE DATABASE IF NOT EXISTS crypto_db;
USE crypto_db;

CREATE TABLE IF NOT EXISTS cryptocurrencies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    coin_id VARCHAR(255) NOT NULL UNIQUE,
    ticker VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(20,8) NOT NULL,
    change_24h DECIMAL(10,4) NOT NULL,
    market_cap DECIMAL(20,2) NOT NULL,
    volume_24h DECIMAL(20,2) NOT NULL,
    sparkline TEXT,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);